export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  CCABR_ELO_EXECUTIVO_AVANCADO = 'ROLE_CCABR_ELO_EXECUTIVO_AVANCADO',
  CCABR_ELO_EXECUTIVO_BASICO = 'ROLE_CCABR_ELO_EXECUTIVO_BASICO',
}
