package com.ecursos.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CapacitacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapacitacaoAllPropertiesEquals(Capacitacao expected, Capacitacao actual) {
        assertCapacitacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertCapacitacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapacitacaoAllUpdatablePropertiesEquals(Capacitacao expected, Capacitacao actual) {
        assertCapacitacaoUpdatableFieldsEquals(expected, actual);
        assertCapacitacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapacitacaoAutoGeneratedPropertiesEquals(Capacitacao expected, Capacitacao actual) {
        assertThat(expected)
            .as("Verify Capacitacao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapacitacaoUpdatableFieldsEquals(Capacitacao expected, Capacitacao actual) {
        assertThat(expected)
            .as("Verify Capacitacao relevant properties")
            .satisfies(e -> assertThat(e.getCapacitacaoStatus()).as("check capacitacaoStatus").isEqualTo(actual.getCapacitacaoStatus()))
            .satisfies(e -> assertThat(e.getSigpes()).as("check sigpes").isEqualTo(actual.getSigpes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapacitacaoUpdatableRelationshipsEquals(Capacitacao expected, Capacitacao actual) {
        assertThat(expected)
            .as("Verify Capacitacao relationships")
            .satisfies(e -> assertThat(e.getMilitar()).as("check militar").isEqualTo(actual.getMilitar()))
            .satisfies(e -> assertThat(e.getTurma()).as("check turma").isEqualTo(actual.getTurma()));
    }
}
