package com.ecursos.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoAllPropertiesEquals(Tipo expected, Tipo actual) {
        assertTipoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoAllUpdatablePropertiesEquals(Tipo expected, Tipo actual) {
        assertTipoUpdatableFieldsEquals(expected, actual);
        assertTipoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoAutoGeneratedPropertiesEquals(Tipo expected, Tipo actual) {
        assertThat(expected)
            .as("Verify Tipo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoUpdatableFieldsEquals(Tipo expected, Tipo actual) {
        assertThat(expected)
            .as("Verify Tipo relevant properties")
            .satisfies(e -> assertThat(e.getCategoria()).as("check categoria").isEqualTo(actual.getCategoria()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoUpdatableRelationshipsEquals(Tipo expected, Tipo actual) {
        // empty method
    }
}
