export enum ForcaEnum {
  MARINHA_DO_BRASIL = 'MARINHA_DO_BRASIL',

  EXERCITO_BRASILEIRO = 'EXERCITO_BRASILEIRO',

  FORCA_AEREA_BRASILEIRA = 'FORCA_AEREA_BRASILEIRA',

  POLICIA_MILITAR = 'POLICIA_MILITAR',

  CORPO_DE_BOMBEIROS = 'CORPO_DE_BOMBEIROS',

  ORGAO_CIVIL_BRASILEIRO = 'ORGAO_CIVIL_BRASILEIRO',

  ORGAO_ESTRANGEIRO = 'ORGAO_ESTRANGEIRO',
}
