export enum StatusCursoEnum {
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',

  AGUARDANDO_BCA_APROVACAO = 'AGUARDANDO_BCA_APROVACAO',

  CANCELADO = 'CANCELADO',

  CONCLUIDO = 'CONCLUIDO',

  EM_ANDAMENTO = 'EM_ANDAMENTO',

  INDICACAO_NAO_APROVADA_PELA_ORGANIZACAO_DO_CURSO = 'INDICACAO_NAO_APROVADA_PELA_ORGANIZACAO_DO_CURSO',

  INDICACAO_QUANDO_CHEGAR_APROVACAO = 'INDICACAO_QUANDO_CHEGAR_APROVACAO',

  INDICACAO = 'INDICACAO',

  APROVADO = 'APROVADO',
}
