export enum StatusEnum {
  CONCLUIDO = 'CONCLUIDO',

  APROVADO = 'APROVADO',

  REPROVADO = 'REPROVADO',

  EM_ANDAMENTO = 'EM_ANDAMENTO',

  INDICADO = 'INDICADO',

  INDICACAO_NAO_APROVADA_PELA_ORGANIZACAO_DO_CURSO = 'INDICACAO_NAO_APROVADA_PELA_ORGANIZACAO_DO_CURSO',

  MATRICULADO = 'MATRICULADO',

  NAO_APROVADO_PELA_DTI_COMGAP = 'NAO_APROVADO_PELA_DTI_COMGAP',
}
